// @generated SignedSource<<bc105930a1ac17cb4b39c19ff7556fda>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater scm/mononoke/github_mirror/github_mirror.thrift
//
// Source: https://www.internalfb.com/code/configerator/[master]/source/scm/mononoke/github_mirror/github_mirror.thrift
include "thrift/annotation/rust.thrift"
include "thrift/annotation/thrift.thrift"

@thrift.AllowLegacyMissingUris
package;

// How sync from GitHub to Mononoke is triggered for a given mirror.
//
// WEBHOOK_ONLY (the default when unset) is appropriate for the vast
// majority of mirrors. POLLING_ONLY and BOTH should be opt-in for
// specific repos because polling cost grows linearly with repo count
// and becomes meaningful at thousands-of-repos scale.
enum SyncTrigger {
  WEBHOOK_ONLY = 0,
  POLLING_ONLY = 1,
  BOTH = 2,
}

// Marker variant for ImportRefs::all. Empty by design — its presence
// (not its content) is the signal.
@rust.Exhaustive
struct AllRefs {}

// Which refs to mirror. Either every ref (all branches and tags) or an
// explicit list of ref names (e.g., ["refs/heads/main", "refs/tags/v1"]).
//
// Modeled as a union so the "all" case is type-explicit instead of
// inferred from an empty list, and so additional selection modes (e.g.,
// glob patterns) can be added later as new variants without changing
// existing entries.
union ImportRefs {
  1: AllRefs all;
  2: list<string> specific;
}

// Per-mirror metadata for a single GitHub-to-Mononoke mirror.
//
// The repo name itself is the map key in `GithubMirrorRegistry.entries`
// and is identical on both sides — `<github_org>/<name>` on GitHub and
// the same on Mononoke.
@rust.Exhaustive
struct GithubMirrorEntry {
  // Oncall name for the upstream MSL team owning this mirror.
  // Used for routing alerts on sync failures and for handoff context.
  1: optional string owner_oncall;
  // When this registry entry was first added, Unix epoch seconds.
  // Optional; older entries may omit it.
  2: optional i64 created_at_unix_seconds;
  // Trigger mode for syncing this mirror. Unset = WEBHOOK_ONLY.
  // Polling is opt-in to avoid unbounded cost growth as repo count scales.
  3: optional SyncTrigger sync_trigger;
  // Which refs to mirror — either every ref or an explicit list. See the
  // ImportRefs union above. Required: every entry must explicitly choose,
  // either ImportRefs(all=AllRefs()) or ImportRefs(specific=[...]).
  //
  // Applied at fetch time as the `git fetch` refspec — for the `specific`
  // variant, only objects reachable from listed refs come over the wire
  // from GitHub, reducing network and storage cost. Also passed to
  // gitimport's --include-refs for belt-and-suspenders bookmark
  // filtering.
  4: ImportRefs import_refs;
}

// Registry of GitHub repos to mirror into Mononoke for a single tenant.
//
// One instance per tenant — MSL gets `msl_mirror_registry.cconf`, future
// tenants (e.g., AIDevX) get their own `<tenant>_mirror_registry.cconf`
// alongside this schema. The schema itself is tenant-agnostic.
//
// Keyed on the repo name (e.g., `PAR/ecto1`), which is identical on both
// the GitHub side and the Mononoke side. The webhook handler looks up
// an entry by the GitHub repo from the incoming payload; the polling
// job and bulk provisioner iterate all entries.
@rust.Exhaustive
struct GithubMirrorRegistry {
  1: map<string, GithubMirrorEntry> entries;
}
